config/routes.rb
Rails.application.routes.draw do
  devise_for :dashboards
  get '/bookings/display', to: 'bookings#display'
  root  "homes#index"
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        passwords: 'users/passwords',
        registrations: 'users/registrations'
      }
  resources :trips
  resources :destinations
  resources :restaurants
  resources :homes
  resources :bookings
  resources :abouts
  resources :admins
  resources :user_bookings
  get '/users/display', to: 'users#display'

  post '/trips/search', to: 'trips#search'
  get '/trips/about', to: 'trips#about'
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :destination_trips
  has_many :destinations, through: :destination_trips
  # has_one :home,  dependent: :destroy
  has_one_attached :main_image
  has_many :bookings
  has_many :users, through: :bookings
  validates :trip_name, uniqueness: true
  validates :amount, numericality: { greater_than: 2000}

  scope :filter_by_amount, -> (min, max) { where('amount >= ? AND amount <= ?', min, max) }
  scope :filter_by_trip_type, -> (trip_type) { where('trip_type = ?', trip_type) }
  scope :filter_by_start_and_end_date, -> (start_date, end_date) { where("start_date >= ? AND end_date <= ?", start_date, end_date) }
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def index 
    @trip = Trip.all
    filter_trips(params)
    # if @trip.present?
    #   respond_to do |format|
    #     format.json { render json: @trip, each_serializer: TripSerializer }
    #     format.html { render :index }
    #   end
    # else
    #   render json: {message: 'Trip Not Found'}, status: 404
    # end
  end

  def show 
    @trip = Trip.find_by(id: params[:id])
    if @trip.present?
      respond_to do |format|
      format.json { render :json => @trip }
      format.html { render :show }
      end
    else  
      render json: {message: 'Trip Not Found'}, status: 404
    end
  end

  def new
    @trip = Trip.new
  end

  def create
    params[:destination_id]
    @trip = Trip.new(trip_params)
    if @trip.save
      params[:destination_id].each do |destination_id|
        @trip.destination_trips.create(destination_id: destination_id)
      end if params[:destination_id].any?
      redirect_to root_path
    else
      render :index, status: :unprocessable_entity
    end
  end
   

  def edit
    @trip = Trip.find(params[:id])
  end

  def update
    @trip = Trip.find(params[:id])

    if @trip.update(trip_params)
      redirect_to trips_path
    else
      render :edit, status: :unprocessable_entity
    end
  end
  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy

    redirect_to trips_path, status: :see_other
  end
  def search
    redirect_to trips_path(start_date: params[:start_date], end_date: params[:end_date], search: params[:search], trip_type: params[:trip_type], min: params[:min], max: params[:max])
  end

  private

  def trip_params
    params.require(:trip).permit(:trip_type, :trip_name, :amount, :start_date, :end_date, :main_image, destination_id: [])
  end

  def filter_trips(params)
    @trip = @trip.joins(:destinations).where(destinations: { city_name: params[:search] }) if !params[:search].blank?
    # @trip = @trip.where(trip_type: params[:trip_type]) if !params[:trip_type].blank?
    # @trip = @trip.where("start_date >= :start_date AND end_date <= :end_date",
    #   {start_date: params[:start_date], end_date: params[:end_date]}) if !params[:start_date].blank? && !params[:end_date].blank?
    # @trip = @trip.where('amount >= ? AND amount <= ?', params[:min], params[:max]) if !params[:min].blank? && !params[:max].blank?
    # @trip = @trip.where("start_date >= ? AND end_date <= ?", params[:start_date], params[:end_date]) if !params[:start_date].blank? && !params[:end_date].blank?
    @trip = @trip.filter_by_trip_type(params[:trip_type]) if !params[:trip_type].blank?
    @trip = @trip.filter_by_amount(params[:min], params[:max]) if !params[:min].blank? && !params[:max].blank?
    @trip = @trip.filter_by_start_and_end_date(params[:start_date], params[:end_date]) if !params[:start_date].blank? && !params[:end_date].blank?
  end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/edit.html.erb
<h1>New Article</h1>

<%= form_with model: @trip do |form| %>
  <div>
    <%= form.label :trip_name %><br>
    <%= form.text_field :trip_name %>
  </div>

  <div>
    <%= form.label :trip_type %><br>
    <%= form.text_field :trip_type %>
  </div>
  <div>
    <%= form.label :amount %><br>
    <%= form.number_field :amount %>
  </div>
  <div>
    <%= form.label :start_date %><br>
    <%= form.date_field :start_date %>
  </div>
  <div>
    <%= form.label :end_date %><br>
    <%= form.date_field :end_date %>
  </div>

  <br>
  
  <div>
  <%= form.label :add_image %>
  <%= form.file_field :main_image %>
  </div>
  
  <br>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/trips/index.html.erb
<div class = 'container' pt-0>
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= image_tag "lotus.jpeg", size: "1300x500" %>
      <div class="carousel-caption d-none d-md-block">
        <h5>First slide label</h5>
        <p>Some representative placeholder content for the first slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag "mahal.jpeg", size: "1300x500" %>
      <div class="carousel-caption d-none d-md-block">
        <h5>Second slide label</h5>
        <p>Some representative placeholder content for the second slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <%= image_tag "nature.jpeg", size: "1300x500" %>
      <div class="carousel-caption d-none d-md-block">
        <h5>Third slide label</h5>
        <p>Some representative placeholder content for the third slide.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
</div>

<br><br>

<div class='container'>
<%= form_with url: trips_path, method: :get do |form| %>
  <%= form.date_field :start_date, hide_label: true, class: 'datepicker' %>
  <%= form.date_field :end_date, hide_label: true, class: 'datepicker' %>
  <%= form.select :trip_type, ["One Day Trip", "Two Days Trip", "Three Days Trip", "Four Days Trip", "Five Days trip", "Six Days Trip", "Seven Days Trip"],{:prompt => "Select Days Here"} %>   
  <%= form.select :min, ["2000", "5000", "6000", "8000", "10000"],{:prompt => "Minimun Charge"} %>
  <%= form.select :max, ["4000", "6000", "7000", "10000"],{:prompt => "Maximum Charge"} %>
  <%= form.submit 'Search' %> 
<% end %>
</div>
<br><br>

<%# byebug %>


<% if @trip.empty? %>
<p>No Trip Available</p>
<% else %>
<div class ='container'>
</div>
  <div class="container">
  <div class="row row-cols-1 row-cols-md-3">
    <% @trip.each do |trip| %>
        <div class="col-md-4"> 
          <div class="card h-100"> 
            <%= image_tag(trip.main_image,  size: "300x250") if trip.main_image.attached? %> 
            <div class="card-img-overlay"> 
              <h5 class="card-title"><%= link_to trip.trip_name, trip %></h5> 
          </div> 
            <div class="card-body"> 
              <h5 class="card-title"></h5> 
            </div> 
          </div> 
        </div> 
      <% end %>
    </div> 
    </div> 
    
<% end %>

app/views/trips/new.html.erb
<%= link_to "Show All Trips", trips_path %><br>

<h1>Create New Trip</h1>

<%= form_with model: @trip do |form| %>
  <div>
    <%= form.label :trip_name %><br>
    <%= form.text_field :trip_name %>
  </div>

  <div>
    <%= form.label :trip_type %><br>
    <%= form.text_field :trip_type %>
  </div>

  <div>
    <%= form.label :amount %><br>
    <%= form.number_field :amount %>
  </div>
  <div>
    <%= form.label :start_date %><br>
    <%= form.date_field :start_date %>
  </div>
  <div>
    <%= form.label :end_date %><br>
    <%= form.date_field :end_date %>
  </div>

  <br>
  <div>
  <%= form.label :add_image %>
  <%= form.file_field :main_image %>
  </div>


  <br>
   <div>
      <%= select_tag "destination_id[]", options_from_collection_for_select(Destination.all, :id, :city_name),  multiple: true %>
  </div> 
 
  <br>
  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/trips/search.html.erb
<div class="container">
  <div class="row row-cols-1 row-cols-md-3">
    <% @trip.each do |trip| %>
      <div class="col-md-4">
        <div class="card h-100">
          <%= image_tag(trip.main_image,  size: "300x250") if trip.main_image.attached? %>
          <div class="card-img-overlay">
            <h5 class="card-title"><%= link_to trip.trip_name, trip %></h5>
          </div>
          <div class="card-body">
            <h5 class="card-title"></h5>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<%= @trip.city_name %>

app/views/trips/show.html.erb
<h2>Trip Details</h2>
<%= image_tag(@trip.main_image,  size: "200x200") if @trip.main_image.attached? %>
<br>
<br>
<table style="width:100%">
  <tr>
    <th>Name</th>
    <th>Type</th>
    <th>Amount</th>
    <th>Start Date</th>
    <th>End Date</th>
    <!-- <th>Destination Id</th> -->
    <th>Destination Name</th>
  </tr>
  <tr>
    <td><%= @trip.trip_name %></td>
    <td><%= @trip.trip_type %></td>
    <td><%= @trip.amount %></td>
    <td><%= @trip.start_date.strftime("%Y-%m-%d") %></td>
    <td><%= @trip.end_date.strftime("%Y-%m-%d") %></td>
    <!-- <td><%#= @trip.destination_id %></td> -->
    <!-- <td><#%= @trip.destination_trips.last&.destination&.city_name %></td>  -->
      <!-- <td> -->
    <td><% @trip.destination_trips.each do |booking| %>
    <%= booking.destination.city_name %><br>
    <% end %></td> 
       
  </tr>
</table>

<br>
<%# if current_user.admin? %>
<!-- <table style="width:100%">
<tr>
<th>Edit Trip</th>
<th>Destroy Trip</th>
<th>Go To All Trip List</th></tr> -->
<!-- <tr> -->
  <td><%#= link_to "Edit Trips", edit_trip_path %></td>
  <td><%#= link_to "Destroy", trip_path(@trip), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></td>
  <td><%#= link_to "Show All Trips", trips_path %></td></tr>
<!-- </table> -->
<%# else %>
<!-- <h4>Book Your Trip Now</h4> -->

<%#= link_to 'Book Your Trip Now' , new_booking_path(trip_id: @trip) %>

<%# end %>


<% if user_signed_in? %>
  <% if current_user.admin? %>
  <table style="width:100%">
  <tr>
  <th>Edit Trip</th>
  <th>Destroy Trip</th>
  <th>Go To All Trip List</th></tr>
  <tr>
    <td><%= link_to "Edit Trips", edit_trip_path %></td>
    <td><%= link_to "Destroy", trip_path(@trip), data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure?"
                    } %></td>
    <%# <td>= link_to "Show All Trips", trips_path</td></tr> %>
    <td><%= link_to "Show All Trips", admins_path %></td></tr>
  </table>
  <% elsif current_user.user? %>
  <h4>Book Your Trip Now</h4>
  <%= link_to 'Book Your Trip Now' , new_booking_path(trip_id: @trip) %>
  <% end %>
  
<% else %>
<h4>Book Your Trip Now</h4>
<%= link_to 'Book Your Trip Now' , new_booking_path(trip_id: @trip) %>
<% end %>