config/routes.rb
Rails.application.routes.draw do
  devise_for :dashboards
  get '/bookings/display', to: 'bookings#display'
  root  "homes#index"
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        passwords: 'users/passwords',
        registrations: 'users/registrations'
      }
  resources :trips
  resources :destinations
  resources :restaurants
  resources :homes
  resources :bookings
  resources :abouts
  resources :admins
  resources :user_bookings
  get '/users/display', to: 'users#display'

  post '/trips/search', to: 'trips#search'
  get '/trips/about', to: 'trips#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :trip
  belongs_to :user
  after_create :generate_unique_token
  @booking
  def generate_unique_token
    # byebug
    charset = %w{ 2 3 4 6 7 9 A C D E F G H J K M N P Q R T V W X Y Z}
    @a = (0...8).map{ charset.to_a[rand(charset.size)] }.join
    self.booking_token = @a
    self.save
  end
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/destination.rb
class Destination < ApplicationRecord
  has_many :destination_trips
  has_many :trips, through: :destination_trips
  has_one :hotel
end

app/models/destination_trip.rb
class DestinationTrip < ApplicationRecord
  belongs_to :trip
  belongs_to :destination
end

app/models/home.rb
class Home < ApplicationRecord
  # has_one :trip
  # belongs_to :trip
  # has_one_attached :main_image
end

app/models/hotel.rb
class Hotel < ApplicationRecord
end

app/models/trip.rb
class Trip < ApplicationRecord
  has_many :destination_trips
  has_many :destinations, through: :destination_trips
  # has_one :home,  dependent: :destroy
  has_one_attached :main_image
  has_many :bookings
  has_many :users, through: :bookings
  validates :trip_name, uniqueness: true
  validates :amount, numericality: { greater_than: 2000}

  scope :filter_by_amount, -> (min, max) { where('amount >= ? AND amount <= ?', min, max) }
  scope :filter_by_trip_type, -> (trip_type) { where('trip_type = ?', trip_type) }
  scope :filter_by_start_and_end_date, -> (start_date, end_date) { where("start_date >= ? AND end_date <= ?", start_date, end_date) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :trips, through: :bookings
  after_create :welcome_email
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  enum role: [:user, :admin]
  after_initialize do
    if self.new_record?
      self.role ||= :user
    end
  end  

  def welcome_email
    # @email = self.email
    UserMailer.welcome_email(self).deliver_now
    # UserMailer.with(@email).welcome_email.deliver_now

  end
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  def index 
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
    @trip = Trip.all
  end
  def show 
    @trip = Trip.find(params[:id])
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  def index 
    @trip = Trip.all
    filter_trips(params)
    # if @trip.present?
    #   respond_to do |format|
    #     format.json { render json: @trip, each_serializer: TripSerializer }
    #     format.html { render :index }
    #   end
    # else
    #   render json: {message: 'Trip Not Found'}, status: 404
    # end
  end

  def show 
    @trip = Trip.find_by(id: params[:id])
    if @trip.present?
      respond_to do |format|
      format.json { render :json => @trip }
      format.html { render :show }
      end
    else  
      render json: {message: 'Trip Not Found'}, status: 404
    end
  end

  def new
    @trip = Trip.new
  end

  def create
    params[:destination_id]
    @trip = Trip.new(trip_params)
    if @trip.save
      params[:destination_id].each do |destination_id|
        @trip.destination_trips.create(destination_id: destination_id)
      end if params[:destination_id].any?
      redirect_to root_path
    else
      render :index, status: :unprocessable_entity
    end
  end
   

  def edit
    @trip = Trip.find(params[:id])
  end

  def update
    @trip = Trip.find(params[:id])

    if @trip.update(trip_params)
      redirect_to trips_path
    else
      render :edit, status: :unprocessable_entity
    end
  end
  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy

    redirect_to trips_path, status: :see_other
  end
  def search
    redirect_to trips_path(start_date: params[:start_date], end_date: params[:end_date], search: params[:search], trip_type: params[:trip_type], min: params[:min], max: params[:max])
  end

  private

  def trip_params
    params.require(:trip).permit(:trip_type, :trip_name, :amount, :start_date, :end_date, :main_image, destination_id: [])
  end

  def filter_trips(params)
    @trip = @trip.joins(:destinations).where(destinations: { city_name: params[:search] }) if !params[:search].blank?
    # @trip = @trip.where(trip_type: params[:trip_type]) if !params[:trip_type].blank?
    # @trip = @trip.where("start_date >= :start_date AND end_date <= :end_date",
    #   {start_date: params[:start_date], end_date: params[:end_date]}) if !params[:start_date].blank? && !params[:end_date].blank?
    # @trip = @trip.where('amount >= ? AND amount <= ?', params[:min], params[:max]) if !params[:min].blank? && !params[:max].blank?
    # @trip = @trip.where("start_date >= ? AND end_date <= ?", params[:start_date], params[:end_date]) if !params[:start_date].blank? && !params[:end_date].blank?
    @trip = @trip.filter_by_trip_type(params[:trip_type]) if !params[:trip_type].blank?
    @trip = @trip.filter_by_amount(params[:min], params[:max]) if !params[:min].blank? && !params[:max].blank?
    @trip = @trip.filter_by_start_and_end_date(params[:start_date], params[:end_date]) if !params[:start_date].blank? && !params[:end_date].blank?
  end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/admins/index.html.erb
<table>
  <tr>
    <th>Trip List</th>
    <th>Add new Trip Here</th>
    <th>Add Destination</th>
  </tr>
  <tr> 
    <td>
      <% @trip.each do |trip| %><br> 
      <%= link_to trip.trip_name, trip %>
      <% end %> 
    </td> 
    <td><%= link_to "Add Trip", new_trip_path %><br> 
</td>
<td><%= link_to "Show All Destination", destinations_path %></td> 
</tr>
</table> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

 <!-- <link href = 'https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/11.0.2/bootstrap-slider.min.js'> -->
  

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <%= javascript_include_tag "/javascript/javascript" %>

  </head>

  <body>

  <%= render 'shared/header' %>
  <div class='container'>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
      </div> 
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-slider/11.0.2/bootstrap-slider.js"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  </head>

  <body>

  <!-- <%#= render 'shared/dashboard' %> -->
  <div class='container'>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
      </div> 
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/shared/_dashboard.html.erb
<!-- <div class="container">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
  <#%= image_tag "logo.png", size: "70x70" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <#%= link_to "Home", root_path,class: 'nav-link' %>

          
        </li>
        <li class="nav-item">
        <#%= link_to "About", root_path,class: 'nav-link' %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-link"
        <%# if user_signed_in? %>
          <li class="nav-item">
            <#%= link_to 'Logout', destroy_user_session_path, data: { turbo_method: :delete} %>
          </li>
        <#% else %>
            <li class="nav-item">
            <#%= link_to 'Sign Up', new_user_registration_path %>
            </li>
            <li class="nav-item">
            <%#= link_to 'Login', new_user_session_path %>
            </li>
         <#% end %>
        </li>
    
       
      </ul>
      
    </div>
  </div>
</nav>
</div> -->

<!-- <div class = 'container' pt-0>
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%#= image_tag "lotus.jpeg", size: "1300x500" %>
      <div class="carousel-caption d-none d-md-block">
        <h5>First slide label</h5>
        <p>Some representative placeholder content for the first slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <%#= image_tag "mahal.jpeg", size: "1300x500" %>
      <div class="carousel-caption d-none d-md-block">
        <h5>Second slide label</h5>
        <p>Some representative placeholder content for the second slide.</p>
      </div>
    </div>
    <div class="carousel-item">
      <%#= image_tag "nature.jpeg", size: "1300x500" %>
      <div class="carousel-caption d-none d-md-block">
        <h5>Third slide label</h5>
        <p>Some representative placeholder content for the third slide.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

</div> -->
<!-- # <div class='container'>
# <h1>Welcome Admin</h1>
# </div>
# <div class='container'>
#  <#%= link_to "Create Trips", trips_path %>
# </div>
# <div class='container'>
#  <#%= link_to "Add Cities For Your Trips", trips_path %>
# </div> -->

app/views/shared/_header.html.erb
<div class="container">
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
  <%= image_tag "logo.png", size: "60x60" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item">
        <%= link_to "Home", root_path,class: 'nav-link' %>
        </li>
        <li class="nav-item">
        <%= link_to "About", abouts_path,class: 'nav-link' %>
        </li>
        
         <div class="d-flex">
          <%= form_tag(trips_search_path, method: 'post', authenticity_token: false) do %>
          <div class='input-group'> 
            <%= text_field_tag(:search, params[:search], class: "form-control me-1", type: "search", placeholder: "Search by Destintaion,range or date") %>
            <%= submit_tag("Search", class: "btn btn-outline-success") %>
          </div> 
          <% end %> 
         </div> 
       

       <li class="nav-item">
        <% if user_signed_in? %>

        <%# <li class="nav-link"> %>

          <%= link_to 'Logout', destroy_user_session_path, data: { turbo_method: :delete}, class: 'nav-link' %>
        </li>
          <%if current_user.admin? %>
           <li class="nav-item">
          <%= link_to "All Trips", admins_path,class: 'nav-link' %>
          </li>
          <% else %>
           <li class="nav-item">
          <%= link_to "Bookings", bookings_path,class: 'nav-link' %>
          </li>


          <% end %>
          <li class="nav-item">
          <%= current_user.first_name %>
          </li>
        <% else %>
            <li class="nav-item">
              <%= link_to 'Sign Up', new_user_registration_path,class: 'nav-link' %>
            </li>
            <li class="nav-item">
            <%= link_to 'Login', new_user_session_path,class: 'nav-link' %>
            </li>
        <% end %>
        </li>
        

        </form>
      </ul>
    </div>
  </div>

</nav>
</div>