config/routes.rb
Rails.application.routes.draw do
  devise_for :dashboards
  get '/bookings/display', to: 'bookings#display'
  root  "homes#index"
  devise_for :users, controllers: {
        sessions: 'users/sessions',
        passwords: 'users/passwords',
        registrations: 'users/registrations'
      }
  resources :trips
  resources :destinations
  resources :restaurants
  resources :homes
  resources :bookings
  resources :abouts
  resources :admins
  resources :user_bookings
  get '/users/display', to: 'users#display'

  post '/trips/search', to: 'trips#search'
  get '/trips/about', to: 'trips#about'
end

app/models/destination.rb
class Destination < ApplicationRecord
  has_many :destination_trips
  has_many :trips, through: :destination_trips
  has_one :hotel
end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
  def index 
    @destination = Destination.all
  end
  def show 
    @destination = Destination.find(params[:id])
  end
  def new
    @destination = Destination.new
  end

  def create
    @destination = Destination.new(destination_params)
    if @destination.save
      # byebug
      @destination.create_hotel(hotel_name: params[:hotel][:hotel_name])
      redirect_to destinations_path
    else
      render :index, status: :unprocessable_entity
    end
  end

  def edit
    @destination = Destination.find(params[:id])
  end

  def update
    @destination = Destination.find(params[:id])

    if @destination.update(destination_params)
      redirect_to destinations_path
    else
      render :edit, status: :unprocessable_entity
    end
  end
  def destroy
    @destination = Destination.find(params[:id])
    @destination.destroy

    redirect_to destinations_path, status: :see_other
  end
  private
  def destination_params
    params.require(:destination).permit(:city_name, :state_name)
  end

end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/views/destinations/edit.html.erb
<h1>Create New Destination</h1>

<%= form_with model: @destination do |form| %>
  <div>
    <%= form.label :city_name %><br>
    <%= form.text_field :city_name %>
  </div>

  <div>
    <%= form.label :state_name %><br>
    <%= form.text_field :state_name %>
  </div>

  <br>
  <div>
    <%= form.submit %>
  </div>
 
<% end %><br>
<%= link_to "Show All Destinations ", destinations_path %><br>

app/views/destinations/index.html.erb
<table>
  <tr>
    <th>Destination List</th>
  </tr>
  <tr>
    <td>
        <% @destination.each do |x| %><br>
      <%= link_to x.city_name, x %>
      <% end %>
    </td>
  </tr>
</table>

<br>

<table style="width:100%">
<tr>
<th>Add new Trip Here</th>
<tr>
<td><%= link_to "Show Trip", trips_path %><br>
</td>
<td><%= link_to "Add Destination", new_destination_path %><br>
</td>
</table>

app/views/destinations/new.html.erb
<h1>Create New Destination</h1>

<%= form_with model: @destination do |form| %>
  <div>
    <%= form.label :city_name %><br>
    <%= form.text_field :city_name %>
  </div>

  <div>
    <%= form.label :state_name %><br>
    <%= form.text_field :state_name %>
  </div>
  
  <%= fields_for :hotel, @destination.hotel do |hotel_name| %>
  <%= hotel_name.label :hotel_name %><br>
  <%= hotel_name.text_field :hotel_name %><br>
  <% end %>

  <br>
  <div>
    <%= form.submit %>
  </div>
 
<% end %><br>
<%= link_to "Show All Destinations ", destinations_path %><br>

app/views/destinations/show.html.erb
<h2>Destination Details</h2>

<table style="width:100%">
  <tr>
    <th>Destination Name</th>
    <th>Hotel Name</th>
    
  </tr>
  <tr>
    <td><%= @destination.city_name %></td>
    <td><%= @destination.hotel.hotel_name %></td>
   
  </tr>
  
</table>

<br>
<table style="width:100%">
<tr>
<th>Edit Destination</th>
<th>Destroy Destination</th>
<th>Go To All Trip List</th></tr>
<tr>
<td><%= link_to "Edit Destination", edit_destination_path %></td>
<td><%= link_to "Destroy", destination_path(@destination), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></td>
<td><%= link_to "Show All Trips", destinations_path %></td></tr>
</table>